targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[licenses]
unlicensed = "deny"
allow = ["GPL-3.0-or-later", "MIT", "ISC", "Unicode-DFS-2016", "BSD-2-Clause", "BSD-3-Clause"]